import anon from "../Sidebar/assets/anonymous.svg";
export const data = [
  { name: "Konstantin", image: anon },
  { name: "Aleksei", image: anon },
  { name: "Irina", image: anon },
  { name: "Aleksandr", image: anon },
  { name: "Nikita", image: anon },
  { name: "Artur", image: anon },
  { name: "Micheal", image: anon },
  { name: "James", image: anon },
  { name: "Aita", image: anon },
  { name: "Mark", image: anon },
  { name: "Joshua", image: anon },
  { name: "Rock", image: anon },
  { name: "Salmon", image: anon },
  { name: "Stranger", image: anon },
  { name: "Intro", image: anon },
  { name: "LOTR", image: anon },
  { name: "Miseal", image: anon },
  { name: "Ronie", image: anon },
  { name: "Romia", image: anon },
  { name: "Jake", image: anon },
  { name: "Paul", image: anon },
  { name: "Rose", image: anon },
  { name: "Linda", image: anon },
  { name: "Shark", image: anon },
  { name: "Water", image: anon },
];
